services:
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
 
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  kafka-init:
    image: apache/kafka:latest
    depends_on:
      - kafka
    entrypoint: ['/bin/sh', '-c']
    restart: no
    command: |
      "
      echo 'Waiting for Kafka to be ready...'
      while ! nc -z kafka 19092; do sleep 1; done
      echo 'Creating topic...'
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic my-topic --partitions 1 --replication-factor 1 --bootstrap-server kafka:19092
      "
        
